rootfs:
  rootfsPath: '/home/ubuntu/rootfs'
  workDir: '/home/w' # Work directory in rootfs
  containerFilesPath: '/home/ubuntu/containerFiles'
  workUser: 'test' # user in rootfs, used in execution
mq:
  ip: '127.0.0.1'
  port: 5672
  userName: 'guest'
  password: 'guest'
dataFilesPath: '/home/ubuntu/dataFiles'
cacheFilesPath: '/home/ubuntu/cacheFiles'
